@startuml
title Жизненный цикл

start
:Создать GameManager;
:Получить число клиентов и кассиров;
if (Введён 0?) then (да)
  :Выбрать случайное значение
  в допустимом диапазоне;
endif
:Создать клиентов и поместить
их в конец очереди;
:Создать объекты Cashier;
:Запустить поток для каждой кассы;

repeat
  :Под блокировкой queue_mutex
  проверить, пуста ли очередь;
  if (Все клиенты обслужены
  и очередь пуста?) then (да)
    break
  endif
  if (Есть клиенты, но нет
  активных касс?) then (да)
    :Сообщить о невозможности
    продолжения;
    break
  endif
  if (Есть команда из консоли?) then (да)
    :Обработать команду;
    switch (Команда)
    case (marina)
      :Создать кассу и поток;
    case (galya <id>)
      :Запросить отмену обслуживания;
    case (add)
      :Добавить клиента в хвост очереди;
    case (obed <id>)
      :Запросить остановку кассы,
      если активна ещё хотя бы одна;
    case (другая)
      :Вывести сообщение об ошибке;
    endswitch
  endif
  :Ожидать 200 мс;
repeat while (Симуляция продолжается?) is (да)

:Запросить остановку всех касс;
:Дождаться завершения потоков (join);
:Вывести «All clients served. Game over.»;
stop
@enduml
